DROP TABLE IF EXISTS program;
DROP TABLE IF EXISTS channel;
DROP TABLE IF EXISTS video;

CREATE TABLE program (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL
);
CREATE TABLE channel (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL
);

CREATE TABLE video (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  program_id INTERGER,
  broadcast_at TIMESTAMP NOT NULL,
  channel_id INTERGER,
  filename TEXT DEFAULT NULL,
  duration TEXT DEFAULT NULL,
  url TEXT DEFAULT NULL,
  status INTERGER DEFAULT 0 NOT NULL,
  FOREIGN KEY (program_id) REFERENCES program (id),
  FOREIGN KEY (channel_id) REFERENCES channel (id)
);